### PR TITLE
Fix/add steamvr driver manifest

### PR DESCRIPTION
**Pull request by Rexios80**
I hadn't touched the driver in a while and I tried to get it working again but it refused. I saw that other drivers had a `driver.vrdrivermanifest` file but the leap motion driver did not. Adding this file made the driver work for me again. I'm really not sure why it stopped working.

### CODE REVIEW

**Review by SDraw — APPROVED** [review]

**Comment by SDraw** [comment]
Somehow AppVeyor can't open solution for VS2019 auto-building. I'll try to set build for VS2017, but SDK compatibility list is a total mess.

**Comment by Rexios80** [comment]
Sorry I know the VS update should have been a different PR but I needed it to be up to date for the compiled dll to actually work.

**Comment by Rexios80** [comment]
I also wonder if the compiled dlls would work on all machines now. Might be helpful for people who don't know how to use VS for you to make a new release.

**Comment by SDraw** [comment]
Actually, setting VS version to 2019 as default in projects isn't a bad idea. Still, manual building is requirement now, but commits are pushed that often. I'd better supply different VS builds in releases from now on.

**Pull request merged**
